// TP-12 — structural spec for the 90 records authored in this phase.
// This file is the single source of truth for everything MACHINE-critical
// in a record: classification, applyOrder, inputs schema, suggest rule,
// interactions, and golden-test case definitions. The scaffold script
// stamps these into content skeletons; prose authors never touch them.
// Golden expected deltas are computed by scripts/embed-goldens.mjs
// through the real engine — never by hand, never by a model.

// ── canonical golden profiles ────────────────────────────────────────────
export const base = (over = {}) => ({
  filingStatus: 'single',
  state: null,
  wages: 0,
  businesses: [],
  rentals: [],
  interestIncome: 0,
  ordinaryDividends: 0,
  qualifiedDividends: 0,
  shortTermCapGain: 0,
  longTermCapGain: 0,
  otherIncome: 0,
  adjustments: 0,
  seHealthInsurance: 0,
  retirementContributions: 0,
  hsaContribution: 0,
  itemized: { stateLocalTaxesPaid: 0, mortgageInterest: 0, charitable: 0, other: 0 },
  dependentsUnder17: 0,
  otherDependents: 0,
  withholding: 0,
  estimatedPayments: 0,
  qbiReduction: 0,
  otherCredits: 0,
  corpTaxPaid: 0,
  otherTaxes: 0,
  ptetPaid: 0,
  ...over,
});

export const schC = (netProfit, over = {}) => ({
  id: 'b1',
  name: 'Business',
  kind: 'schedule-c',
  netProfit,
  employeeWages: 0,
  ownerWages: 0,
  sstb: false,
  qbiEligible: true,
  ...over,
});

export const sCorp = (netProfit, ownerWages, over = {}) => ({
  id: 's1',
  name: 'S corp',
  kind: 's-corp',
  netProfit,
  employeeWages: 0,
  ownerWages,
  sstb: false,
  qbiEligible: true,
  ...over,
});

export const rental = (netIncome, over = {}) => ({
  id: 'r1',
  name: 'Rental',
  netIncome,
  activeParticipant: true,
  ...over,
});

// Common baselines
const CHC300 = () => base({ filingStatus: 'mfj', businesses: [schC(300_000)] });
const CHC150 = () => base({ businesses: [schC(150_000)] });
const SC300 = () => base({ filingStatus: 'mfj', businesses: [sCorp(300_000, 100_000)] });
const SC200 = () => base({ businesses: [sCorp(200_000, 80_000)] });
const W2GAIN = () =>
  base({ filingStatus: 'mfj', wages: 250_000, longTermCapGain: 150_000 });


const inputs = (properties, required = Object.keys(properties)) => ({
  type: 'object',
  properties,
  required,
});
const money = (min = 0) => ({ type: 'number', minimum: min });

// ── the spec ─────────────────────────────────────────────────────────────
// Modeled entries carry: applyOrder, inputs, suggest, cases (2+),
// mayIncreaseBurden where honest modeling can raise the current-year
// burden. Advisory entries carry: suggest only.
export const SPEC = [
  // ═══ business-expenses ═══
  {
    id: '163j-planning',
    name: 'Business Interest Limitation (§163(j)) Planning',
    category: 'business-expenses',
    modeled: false,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'structural',
    effort: 'multi-step',
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 1_000_000 }],
      reason: 'Larger businesses with leverage should confirm §163(j) headroom before financing decisions.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['equipment-timing'] },
  },
  {
    id: 'achievement-awards',
    name: 'Employee Achievement Awards',
    category: 'business-expenses',
    modeled: false,
    complexity: 1,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'Employers with staff can deduct tangible achievement awards that employees exclude.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['de-minimis-fringe'] },
  },
  {
    id: 'bad-debt-review',
    name: 'Bad Debt Deduction Review (Accrual)',
    category: 'business-expenses',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    applyOrder: 34,
    inputs: inputs({ worthlessAmount: money() }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Accrual-method businesses often carry receivables that are already worthless and deductible.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['cash-vs-accrual'] },
    cases: [
      { name: 'mfj Sch C 300k, 20k written off', profile: CHC300(), params: { worthlessAmount: 20_000 } },
      { name: 'single S-corp 200k/80k, 8k written off', profile: SC200(), params: { worthlessAmount: 8_000 } },
    ],
  },
  {
    id: 'cash-vs-accrual',
    name: 'Cash vs. Accrual Method Analysis',
    category: 'business-expenses',
    modeled: false,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 100_000 }],
      reason: 'A method change (Form 3115) can produce a one-time favorable §481(a) adjustment.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['bad-debt-review', 'prepaid-expenses'] },
  },
  {
    id: 'daf-bunching',
    name: 'Charitable Bunching via Donor-Advised Fund',
    category: 'business-expenses',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['individual'],
    savingsBand: '5k-25k',
    effort: 'one-meeting',
    applyOrder: 40,
    inputs: inputs({ contribution: money() }),
    suggest: {
      all: [{ field: 'itemized.charitable', op: 'gt', value: 0 }],
      reason: 'Regular givers can bunch several years of gifts to clear the standard deduction.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['gain-loss-harvesting', 'bracket-management'] },
    cases: [
      {
        name: 'mfj wages 250k, 50k DAF, near-threshold itemizer',
        profile: base({
          filingStatus: 'mfj',
          wages: 250_000,
          itemized: { stateLocalTaxesPaid: 10_000, mortgageInterest: 12_000, charitable: 8_000, other: 0 },
        }),
        params: { contribution: 50_000 },
      },
      {
        name: 'single wages 150k, 25k DAF from standard deduction',
        profile: base({ wages: 150_000, itemized: { stateLocalTaxesPaid: 6_000, mortgageInterest: 0, charitable: 3_000, other: 0 } }),
        params: { contribution: 25_000 },
      },
    ],
  },
  {
    id: 'de-minimis-fringe',
    name: 'De Minimis Fringe Benefits',
    category: 'business-expenses',
    modeled: false,
    complexity: 1,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'Small, infrequent benefits are deductible to the business and tax-free to staff.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['achievement-awards'] },
  },
  {
    id: 'equipment-timing',
    name: 'Equipment Purchase Timing',
    category: 'business-expenses',
    modeled: false,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: '5k-25k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Placed-in-service dates, not payment dates, control the deduction year.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['section-179-expensing', 'bonus-depreciation'] },
  },
  {
    id: 'heavy-vehicle-179',
    name: 'Heavy Vehicle §179 (>6,000 lbs GVWR)',
    category: 'business-expenses',
    modeled: true,
    complexity: 2,
    riskRating: 'moderate',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: '5k-25k',
    effort: 'one-meeting',
    applyOrder: 36,
    inputs: inputs({
      vehicleCost: money(),
      businessUsePct: { type: 'number', minimum: 0, maximum: 100 },
    }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'A >6,000 lb GVWR vehicle used mostly for business escapes the §280F luxury-auto caps.',
    },
    interactions: { requires: [], conflictsWith: ['vehicle-expense-method'], synergiesWith: ['section-179-expensing'] },
    cases: [
      { name: 'mfj Sch C 300k, 90k SUV at 80%', profile: CHC300(), params: { vehicleCost: 90_000, businessUsePct: 80 } },
      { name: 'single Sch C 150k, 70k truck all business', profile: CHC150(), params: { vehicleCost: 70_000, businessUsePct: 100 } },
    ],
  },
  {
    id: 'home-office-deduction',
    name: 'Home Office Deduction (Sole Prop)',
    category: 'business-expenses',
    modeled: true,
    complexity: 1,
    riskRating: 'low',
    entityTypes: ['sole-prop', 'single-member-llc'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    applyOrder: 32,
    inputs: inputs(
      {
        method: { type: 'string', enum: ['simplified', 'actual'] },
        squareFeet: { type: 'number', minimum: 0 },
        actualExpenses: money(),
      },
      ['method'],
    ),
    suggest: {
      all: [{ field: 'hasScheduleC', op: 'eq', value: true }],
      reason: 'Exclusive, regular business use of home space deducts directly on Schedule C.',
    },
    interactions: { requires: [], conflictsWith: ['augusta-rule'], synergiesWith: ['accountable-plan'] },
    cases: [
      { name: 'single Sch C 150k, simplified 300 sq ft', profile: CHC150(), params: { method: 'simplified', squareFeet: 300 } },
      { name: 'mfj Sch C 300k, actual 9k', profile: CHC300(), params: { method: 'actual', actualExpenses: 9_000 } },
    ],
  },
  {
    id: 'inventory-methods',
    name: 'Inventory Method Planning (LIFO/FIFO, UNICAP)',
    category: 'business-expenses',
    modeled: false,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: '5k-25k',
    effort: 'structural',
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 250_000 }],
      reason: 'Inventory-heavy businesses can defer income through method elections.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['cash-vs-accrual'] },
  },
  {
    id: 'meals-optimization',
    name: 'Meals Deduction Optimization',
    category: 'business-expenses',
    modeled: true,
    complexity: 1,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    applyOrder: 34,
    inputs: inputs({ additionalDeduction: money() }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Better meal documentation typically recovers deductions already being spent.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['travel-documentation'] },
    cases: [
      { name: 'mfj Sch C 300k, 6k recovered', profile: CHC300(), params: { additionalDeduction: 6_000 } },
      { name: 'single S-corp 200k/80k, 3k recovered', profile: SC200(), params: { additionalDeduction: 3_000 } },
    ],
  },
  {
    id: 'personal-aircraft',
    name: 'Business Use of Personal Aircraft',
    category: 'business-expenses',
    modeled: true,
    complexity: 5,
    riskRating: 'elevated',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: '25k-100k',
    effort: 'structural',
    applyOrder: 38,
    inputs: inputs({ businessUseDeduction: money() }),
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 500_000 }],
      reason: 'Documented business flight hours can support substantial cost recovery — with heavy substantiation duty.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['bonus-depreciation'] },
    cases: [
      {
        name: 'mfj S-corp 900k/250k comp, 150k aircraft deduction',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(900_000, 250_000)] }),
        params: { businessUseDeduction: 150_000 },
      },
      {
        name: 'mfj S-corp 600k/200k comp, 60k aircraft deduction',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(600_000, 200_000)] }),
        params: { businessUseDeduction: 60_000 },
      },
    ],
  },
  {
    id: 'prepaid-expenses',
    name: 'Prepaid Expense Safe Harbor (12-Month Rule)',
    category: 'business-expenses',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    applyOrder: 35,
    inputs: inputs({ prepaidAmount: money() }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Cash-method businesses can accelerate a year of insurance, rent, and subscriptions.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['equipment-timing', 'bracket-management'] },
    cases: [
      { name: 'mfj Sch C 300k, 15k prepaid', profile: CHC300(), params: { prepaidAmount: 15_000 } },
      { name: 'single Sch C 150k, 6k prepaid', profile: CHC150(), params: { prepaidAmount: 6_000 } },
    ],
  },
  {
    id: 'travel-documentation',
    name: 'Business Travel Optimization (Mixed Trips)',
    category: 'business-expenses',
    modeled: false,
    complexity: 2,
    riskRating: 'moderate',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Primary-purpose planning and day-count records convert mixed trips into deductible travel.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['meals-optimization', 'accountable-plan'] },
  },
  {
    id: 'vehicle-expense-method',
    name: 'Vehicle Expense Method (Standard vs. Actual)',
    category: 'business-expenses',
    modeled: true,
    complexity: 1,
    riskRating: 'low',
    entityTypes: ['sole-prop', 'single-member-llc', 's-corp', 'partnership'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    applyOrder: 34,
    inputs: inputs({ incrementalDeduction: money() }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'The better of standard-mileage vs actual-cost is a yearly comparison worth running.',
    },
    interactions: { requires: [], conflictsWith: ['heavy-vehicle-179'], synergiesWith: ['accountable-plan'] },
    cases: [
      { name: 'single Sch C 150k, 4k incremental', profile: CHC150(), params: { incrementalDeduction: 4_000 } },
      { name: 'mfj Sch C 300k, 7k incremental', profile: CHC300(), params: { incrementalDeduction: 7_000 } },
    ],
  },

  // ═══ credits-incentives ═══
  {
    id: 'childcare-credit-45f',
    name: 'Employer-Provided Childcare Credit (§45F)',
    category: 'credits-incentives',
    modeled: true,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: '25k-100k',
    effort: 'multi-step',
    applyOrder: 72,
    inputs: inputs(
      { qualifiedExpenditures: money(), smallBusiness: { type: 'boolean' } },
      ['qualifiedExpenditures'],
    ),
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'Employers funding childcare capacity or contracts earn a credit of up to 40–50% of the spend.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['dependent-care-fsa'] },
    cases: [
      {
        name: 'mfj S-corp 500k/150k, 100k childcare contract',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(500_000, 150_000, { employeeWages: 200_000 })] }),
        params: { qualifiedExpenditures: 100_000, smallBusiness: true },
      },
      {
        name: 'mfj S-corp 300k/100k, 40k childcare spend',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(300_000, 100_000, { employeeWages: 120_000 })] }),
        params: { qualifiedExpenditures: 40_000 },
      },
    ],
  },
  {
    id: 'disabled-access-credit',
    name: 'Disabled Access Credit (§44)',
    category: 'credits-incentives',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    applyOrder: 73,
    inputs: inputs({ accessExpenditures: money() }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Small businesses making accessibility improvements can claim half the cost, up to $5,000.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: [] },
    cases: [
      { name: 'single Sch C 150k, 10k access spend', profile: CHC150(), params: { accessExpenditures: 10_250 } },
      { name: 'mfj Sch C 300k, 4k access spend', profile: CHC300(), params: { accessExpenditures: 4_000 } },
    ],
  },
  {
    id: 'energy-credits',
    name: 'Business Energy Credits (Solar, EV Charging)',
    category: 'credits-incentives',
    modeled: true,
    complexity: 3,
    riskRating: 'moderate',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    applyOrder: 74,
    inputs: inputs({ creditAmount: money() }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Solar and charging investments still carry credits — with post-OBBBA deadlines to respect.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['bonus-depreciation'] },
    cases: [
      { name: 'mfj S-corp 300k/100k, 18k ITC', profile: SC300(), params: { creditAmount: 18_000 } },
      { name: 'single Sch C 150k, 6k charging credit', profile: CHC150(), params: { creditAmount: 6_000 } },
    ],
  },
  {
    id: 'pfml-credit-45s',
    name: 'Paid Family & Medical Leave Credit (§45S)',
    category: 'credits-incentives',
    modeled: true,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'multi-step',
    applyOrder: 72,
    inputs: inputs(
      {
        leaveWagesPaid: money(),
        paymentRatePct: { type: 'number', minimum: 50, maximum: 100 },
      },
      ['leaveWagesPaid'],
    ),
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'A written paid-leave policy at 50%+ wage replacement earns a 12.5–25% credit on leave wages.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: [] },
    cases: [
      {
        name: 'mfj S-corp 400k/120k, 30k leave wages at 100%',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(400_000, 120_000, { employeeWages: 150_000 })] }),
        params: { leaveWagesPaid: 30_000, paymentRatePct: 100 },
      },
      {
        name: 'mfj S-corp 300k/100k, 12k leave wages at 60%',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(300_000, 100_000, { employeeWages: 90_000 })] }),
        params: { leaveWagesPaid: 12_000, paymentRatePct: 60 },
      },
    ],
  },
  {
    id: 'rd-credit',
    name: 'R&D Tax Credit (§41)',
    category: 'credits-incentives',
    modeled: true,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: '25k-100k',
    effort: 'multi-step',
    applyOrder: 71,
    inputs: inputs({ qre: money(), priorThreeYearAvgQre: money() }, ['qre']),
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 150_000 }],
      reason: 'Development work that resolves technical uncertainty may qualify for the §41 credit.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: [] },
    cases: [
      {
        name: 'mfj S-corp 500k/150k, 200k QRE over 120k avg',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(500_000, 150_000, { employeeWages: 250_000 })] }),
        params: { qre: 200_000, priorThreeYearAvgQre: 120_000 },
      },
      {
        name: 'single Sch C 200k, first-year 80k QRE',
        profile: base({ businesses: [schC(200_000)] }),
        params: { qre: 80_000, priorThreeYearAvgQre: 0 },
      },
    ],
  },
  {
    id: 'state-credits-review',
    name: 'State Credits Review (incl. Idaho PTE Credit)',
    category: 'credits-incentives',
    modeled: false,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: '5k-25k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'State credit menus change yearly and are routinely left unclaimed.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['ptet'] },
  },
  {
    id: 'wotc',
    name: 'Work Opportunity Tax Credit',
    category: 'credits-incentives',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    applyOrder: 71,
    inputs: inputs({ qualifiedFirstYearWages: money() }),
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'Hiring from targeted groups earns up to 40% of first-year wages — if Form 8850 is timely.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: [] },
    cases: [
      {
        name: 'mfj S-corp 400k/120k, 18k certified wages',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(400_000, 120_000, { employeeWages: 160_000 })] }),
        params: { qualifiedFirstYearWages: 18_000 },
      },
      {
        name: 'single Sch C 150k, 6k certified wages',
        profile: base({ businesses: [schC(150_000, { employeeWages: 40_000 })] }),
        params: { qualifiedFirstYearWages: 6_000 },
      },
    ],
  },

  // ═══ entity-structure ═══
  {
    id: 'c-corp-conversion',
    name: 'C-Corp Conversion (Retained Earnings / QSBS)',
    category: 'entity-structure',
    modeled: true,
    complexity: 5,
    riskRating: 'elevated',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'structural',
    effort: 'structural',
    applyOrder: 12,
    mayIncreaseBurden: true,
    inputs: inputs({ salary: money(), dividendDistribution: money() }, ['salary']),
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 400_000 }],
      reason: 'High retained-earnings businesses can weigh the flat 21% rate and a QSBS runway against double tax.',
    },
    interactions: {
      requires: [],
      conflictsWith: ['s-corp-election', 'ptet'],
      synergiesWith: ['qsbs-1202', 'hra-c-corp'],
    },
    cases: [
      {
        name: 'mfj S-corp 600k/180k comp, convert, no dividends',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(600_000, 180_000)] }),
        params: { salary: 180_000, dividendDistribution: 0 },
      },
      {
        name: 'mfj S-corp 600k/180k comp, convert, 100k dividends',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(600_000, 180_000)] }),
        params: { salary: 180_000, dividendDistribution: 100_000 },
      },
    ],
  },
  {
    id: 'holding-management-company',
    name: 'Holding / Management Company Fee Structures',
    category: 'entity-structure',
    modeled: false,
    complexity: 4,
    riskRating: 'elevated',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 500_000 }],
      reason: 'Multi-entity groups can centralize management — with arm’s-length fees and real services.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['multi-entity-structuring'] },
  },
  {
    id: 'late-s-election-relief',
    name: 'Late S-Election Relief (Rev. Proc. 2013-30)',
    category: 'entity-structure',
    modeled: false,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 'single-member-llc', 's-corp'],
    savingsBand: '5k-25k',
    effort: 'one-meeting',
    suggest: {
      all: [
        { field: 'hasBusiness', op: 'eq', value: true },
        { not: { field: 'hasSCorp', op: 'eq', value: true } },
      ],
      reason: 'A missed S-election deadline is usually repairable back to the intended date.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['s-corp-election'] },
  },
  {
    id: 'multi-entity-structuring',
    name: 'Multi-Entity Structuring (OpCo / PropCo Split)',
    category: 'entity-structure',
    modeled: false,
    complexity: 5,
    riskRating: 'moderate',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      all: [
        { field: 'hasBusiness', op: 'eq', value: true },
        { field: 'hasRental', op: 'eq', value: true },
      ],
      reason: 'Separating operations from real estate improves liability walls and exit flexibility.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['self-rental-structuring', 'holding-management-company'] },
  },
  {
    id: 'partnership-vs-s-corp',
    name: 'Partnership vs. S-Corp (Guaranteed Payment Flexibility)',
    category: 'entity-structure',
    modeled: false,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['partnership', 's-corp'],
    savingsBand: 'structural',
    effort: 'multi-step',
    suggest: {
      all: [{ field: 'hasEntity', op: 'eq', value: true }],
      reason: 'Special allocations, basis from debt, and comp flexibility differ sharply between the two.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['s-corp-election'] },
  },
  {
    id: 'self-rental-structuring',
    name: 'Self-Rental Structuring (Real Estate Held Separately)',
    category: 'entity-structure',
    modeled: false,
    complexity: 3,
    riskRating: 'moderate',
    entityTypes: ['s-corp', 'partnership', 'rental'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      all: [
        { field: 'hasBusiness', op: 'eq', value: true },
        { field: 'hasRental', op: 'eq', value: true },
      ],
      reason: 'Owning the building personally and renting to the business needs the self-rental rules managed.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['multi-entity-structuring', 'grouping-election'] },
  },
  {
    id: 'series-llc',
    name: 'Series LLC for Multi-Property Holders',
    category: 'entity-structure',
    modeled: false,
    complexity: 3,
    riskRating: 'moderate',
    entityTypes: ['rental', 'partnership'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      all: [{ field: 'rentals.length', op: 'gt', value: 1 }],
      reason: 'Several properties can sit in one series LLC with per-cell liability separation.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['grouping-election'] },
  },

  // ═══ health-fringe ═══
  {
    id: 'accident-health-c-corp',
    name: 'Accident & Health Plans for C-Corp Owner-Employees',
    category: 'health-fringe',
    modeled: false,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['c-corp'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    suggest: {
      all: [{ field: 'hasEntity', op: 'eq', value: true }],
      reason: 'C-corp owner-employees can receive fully deductible, fully excluded health benefits.',
    },
    interactions: { requires: ['c-corp-conversion'], conflictsWith: [], synergiesWith: ['hra-c-corp'] },
  },
  {
    id: 'dependent-care-fsa',
    name: 'Dependent Care FSA',
    category: 'health-fringe',
    modeled: true,
    complexity: 1,
    riskRating: 'low',
    entityTypes: ['individual'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    applyOrder: 33,
    inputs: inputs({ election: money() }),
    suggest: {
      all: [
        { field: 'wages', op: 'gt', value: 0 },
        { field: 'dependentsUnder17', op: 'gt', value: 0 },
      ],
      reason: 'Up to $7,500 of childcare can run through payroll pre-tax.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['childcare-credit-45f'] },
    cases: [
      {
        name: 'mfj wages 200k, 2 kids, full 7.5k election',
        profile: base({ filingStatus: 'mfj', wages: 200_000, dependentsUnder17: 2 }),
        params: { election: 7_500 },
      },
      {
        name: 'single wages 120k, 1 kid, 5k election',
        profile: base({ wages: 120_000, dependentsUnder17: 1 }),
        params: { election: 5_000 },
      },
    ],
  },
  {
    id: 'disability-insurance-c-corp',
    name: 'C-Corp Paid Disability (Tax-Free Benefits)',
    category: 'health-fringe',
    modeled: false,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasEntity', op: 'eq', value: true }],
      reason: 'Who pays the premium decides whether disability benefits arrive taxed or tax-free.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['accident-health-c-corp'] },
  },
  {
    id: 'group-term-life',
    name: 'Group Term Life (First $50k)',
    category: 'health-fringe',
    modeled: false,
    complexity: 1,
    riskRating: 'low',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'The first $50,000 of employer-paid group term life is deductible and excluded.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['de-minimis-fringe'] },
  },
  {
    id: 'hra-c-corp',
    name: 'HRA for C-Corps',
    category: 'health-fringe',
    modeled: false,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['c-corp'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    suggest: {
      all: [{ field: 'hasEntity', op: 'eq', value: true }],
      reason: 'A C-corp HRA reimburses owner-employee medical costs with full deduction and exclusion.',
    },
    interactions: { requires: ['c-corp-conversion'], conflictsWith: ['section-105-merp'], synergiesWith: ['accident-health-c-corp'] },
  },
  {
    id: 'ichra',
    name: 'ICHRA',
    category: 'health-fringe',
    modeled: true,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    applyOrder: 33,
    inputs: inputs({ annualReimbursements: money() }),
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'Fixed, class-based reimbursement of individual premiums replaces group-plan volatility.',
    },
    interactions: { requires: [], conflictsWith: ['qsehra'], synergiesWith: [] },
    cases: [
      {
        name: 'mfj S-corp 400k/120k, 36k reimbursed',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(400_000, 120_000, { employeeWages: 150_000 })] }),
        params: { annualReimbursements: 36_000 },
      },
      {
        name: 'mfj S-corp 300k/100k, 18k reimbursed',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(300_000, 100_000, { employeeWages: 80_000 })] }),
        params: { annualReimbursements: 18_000 },
      },
    ],
  },
  {
    id: 'qsehra',
    name: 'QSEHRA',
    category: 'health-fringe',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership'],
    savingsBand: 'under-5k',
    effort: 'multi-step',
    applyOrder: 33,
    inputs: inputs({ annualReimbursements: money() }),
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'Employers under 50 lives without a group plan can reimburse premiums within the QSEHRA caps.',
    },
    interactions: { requires: [], conflictsWith: ['ichra'], synergiesWith: [] },
    cases: [
      {
        name: 'mfj Sch C 250k w/ staff, 12k reimbursed',
        profile: base({ filingStatus: 'mfj', businesses: [schC(250_000, { employeeWages: 60_000 })] }),
        params: { annualReimbursements: 12_000 },
      },
      {
        name: 'single S-corp 200k/80k, 6k reimbursed',
        profile: SC200(),
        params: { annualReimbursements: 6_000 },
      },
    ],
  },
  {
    id: 'section-105-merp',
    name: 'Section 105 Medical Reimbursement Plan (Spouse Employee)',
    category: 'health-fringe',
    modeled: true,
    complexity: 3,
    riskRating: 'moderate',
    entityTypes: ['sole-prop'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    applyOrder: 32,
    inputs: inputs({ reimbursedMedical: money() }),
    suggest: {
      all: [
        { field: 'hasScheduleC', op: 'eq', value: true },
        { field: 'filingStatus', op: 'eq', value: 'mfj' },
      ],
      reason: 'A bona fide spouse-employee lets family medical costs become a business deduction that also reduces SE tax.',
    },
    interactions: { requires: ['spouse-payroll'], conflictsWith: ['hra-c-corp'], synergiesWith: ['se-health-insurance'] },
    cases: [
      {
        name: 'mfj Sch C 200k, 15k family medical reimbursed',
        profile: base({ filingStatus: 'mfj', businesses: [schC(200_000, { employeeWages: 12_000 })] }),
        params: { reimbursedMedical: 15_000 },
      },
      {
        name: 'mfj Sch C 120k, 8k reimbursed',
        profile: base({ filingStatus: 'mfj', businesses: [schC(120_000, { employeeWages: 10_000 })] }),
        params: { reimbursedMedical: 8_000 },
      },
    ],
  },
  {
    id: 'section-127-education',
    name: 'Section 127 Educational Assistance',
    category: 'health-fringe',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'multi-step',
    applyOrder: 34,
    inputs: inputs(
      { assistanceAmount: money(), participatingEmployees: { type: 'number', minimum: 1 } },
      ['assistanceAmount'],
    ),
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'Up to $5,250 per employee of tuition or student-loan payments, deductible and excluded.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['kids-401k'] },
    cases: [
      {
        name: 'mfj S-corp 400k/120k, 3 staff at the cap',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(400_000, 120_000, { employeeWages: 150_000 })] }),
        params: { assistanceAmount: 15_750, participatingEmployees: 3 },
      },
      {
        name: 'mfj S-corp 300k/100k, one employee 5,250',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(300_000, 100_000, { employeeWages: 45_000 })] }),
        params: { assistanceAmount: 5_250, participatingEmployees: 1 },
      },
    ],
  },
  {
    id: 'wellness-reimbursements',
    name: 'Wellness Program Reimbursements',
    category: 'health-fringe',
    modeled: false,
    complexity: 2,
    riskRating: 'elevated',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'Legitimate wellness benefits exist — and the marketed double-dip schemes should be declined in writing.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: [] },
  },

  // ═══ income-timing ═══
  {
    id: 'bracket-management',
    name: 'Income Acceleration / Deferral (Bracket Management)',
    category: 'income-timing',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'individual'],
    savingsBand: '5k-25k',
    effort: 'one-meeting',
    applyOrder: 62,
    mayIncreaseBurden: true,
    inputs: inputs({ deferAmount: { type: 'number' } }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Invoice and bonus timing can hold income inside the current bracket — or fill it deliberately.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['prepaid-expenses', 'daf-bunching'] },
    cases: [
      {
        name: 'mfj Sch C 300k + 40k other income deferred',
        profile: base({ filingStatus: 'mfj', otherIncome: 40_000, businesses: [schC(300_000)] }),
        params: { deferAmount: 40_000 },
      },
      {
        name: 'single Sch C 150k, 20k accelerated in',
        profile: CHC150(),
        params: { deferAmount: -20_000 },
      },
    ],
  },
  {
    id: 'crt',
    name: 'Charitable Remainder Trust for Appreciated Assets',
    category: 'income-timing',
    modeled: false,
    complexity: 5,
    riskRating: 'moderate',
    entityTypes: ['individual'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      all: [{ field: 'longTermCapGain', op: 'gt', value: 250_000 }],
      reason: 'A CRT spreads a large gain over years while funding charity and an income stream.',
    },
    interactions: { requires: [], conflictsWith: ['like-kind-1031'], synergiesWith: ['daf-bunching'] },
  },
  {
    id: 'excess-business-loss',
    name: 'Excess Business Loss (§461(l)) Planning',
    category: 'income-timing',
    modeled: false,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership'],
    savingsBand: 'structural',
    effort: 'multi-step',
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'lt', value: 0 }],
      reason: 'Large business losses hit the §461(l) ceiling; the excess becomes an NOL, not a current deduction.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['nol-planning'] },
  },
  {
    id: 'gain-loss-harvesting',
    name: 'Capital Gain & Loss Harvesting',
    category: 'income-timing',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['individual'],
    savingsBand: '5k-25k',
    effort: 'one-meeting',
    applyOrder: 61,
    inputs: inputs({
      shortTermLossHarvested: money(),
      longTermLossHarvested: money(),
    }, []),
    suggest: {
      any: [
        { field: 'shortTermCapGain', op: 'gt', value: 0 },
        { field: 'longTermCapGain', op: 'gt', value: 0 },
      ],
      reason: 'Recognized gains of {longTermCapGain} can absorb unrealized losses before year-end.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['bracket-management', 'daf-bunching'] },
    cases: [
      {
        name: 'mfj wages 250k, 150k LT gain, 60k LT losses',
        profile: W2GAIN(),
        params: { longTermLossHarvested: 60_000 },
      },
      {
        name: 'single wages 150k, 30k ST gain, 25k ST losses',
        profile: base({ wages: 150_000, shortTermCapGain: 30_000 }),
        params: { shortTermLossHarvested: 25_000 },
      },
    ],
  },
  {
    id: 'idgt-installment-sale',
    name: 'Installment Sale to an IDGT (Succession)',
    category: 'income-timing',
    modeled: false,
    complexity: 5,
    riskRating: 'elevated',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 750_000 }],
      reason: 'Selling to a grantor trust freezes estate value while income tax stays with the grantor.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['annual-gifting-program', 'flp-gifting'] },
  },
  {
    id: 'installment-sale-business',
    name: 'Installment Sale on Business Sale',
    category: 'income-timing',
    modeled: true,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['sole-prop', 's-corp', 'partnership'],
    savingsBand: '25k-100k',
    effort: 'structural',
    applyOrder: 63,
    inputs: inputs({
      totalGain: money(),
      termYears: { type: 'number', minimum: 2, maximum: 30 },
    }),
    suggest: {
      all: [{ field: 'longTermCapGain', op: 'gt', value: 200_000 }],
      reason: 'Seller financing spreads a sale gain across years and brackets under §453.',
    },
    interactions: { requires: [], conflictsWith: ['opportunity-zones'], synergiesWith: ['bracket-management'] },
    cases: [
      {
        name: 'mfj 500k business gain over 5 years',
        profile: base({ filingStatus: 'mfj', wages: 120_000, longTermCapGain: 500_000 }),
        params: { totalGain: 500_000, termYears: 5 },
      },
      {
        name: 'mfj 300k gain over 3 years',
        profile: base({ filingStatus: 'mfj', wages: 100_000, longTermCapGain: 300_000 }),
        params: { totalGain: 300_000, termYears: 3 },
      },
    ],
  },
  {
    id: 'like-kind-equipment',
    name: 'Like-Kind Exchanges on Equipment (Post-TCJA Reality)',
    category: 'income-timing',
    modeled: false,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Equipment trades are taxable now — §1031 is real-property-only — so trade-ins need planning, not habit.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['section-179-expensing', 'equipment-timing'] },
  },
  {
    id: 'nol-planning',
    name: 'NOL Carryforward Planning',
    category: 'income-timing',
    modeled: true,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'individual'],
    savingsBand: '25k-100k',
    effort: 'multi-step',
    applyOrder: 64,
    inputs: inputs({ nolCarryforward: money() }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'A carried NOL should be burned deliberately against the right years, not by default.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['excess-business-loss', 'bracket-management'] },
    cases: [
      {
        name: 'mfj Sch C 300k with 150k NOL',
        profile: CHC300(),
        params: { nolCarryforward: 150_000 },
      },
      {
        name: 'single Sch C 150k with 400k NOL (80% limit binds)',
        profile: CHC150(),
        params: { nolCarryforward: 400_000 },
      },
    ],
  },
  {
    id: 'qsbs-1202',
    name: 'QSBS §1202 Exclusion',
    category: 'income-timing',
    modeled: true,
    complexity: 5,
    riskRating: 'moderate',
    entityTypes: ['c-corp', 'individual'],
    savingsBand: '100k-plus',
    effort: 'structural',
    applyOrder: 65,
    inputs: inputs({ eligibleGain: money() }),
    suggest: {
      all: [{ field: 'longTermCapGain', op: 'gt', value: 500_000 }],
      reason: 'Original-issue C-corp stock held five years can exclude gain up to the §1202 ceiling.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['c-corp-conversion'] },
    cases: [
      {
        name: 'mfj 2M QSBS gain fully excluded',
        profile: base({ filingStatus: 'mfj', wages: 200_000, longTermCapGain: 2_000_000 }),
        params: { eligibleGain: 2_000_000 },
      },
      {
        name: 'single 800k of 1M gain qualifies',
        profile: base({ wages: 150_000, longTermCapGain: 1_000_000 }),
        params: { eligibleGain: 800_000 },
      },
    ],
  },

  // ═══ payroll-family ═══
  {
    id: 'board-fees-family',
    name: 'Board of Directors Fees for Family (C-Corp)',
    category: 'payroll-family',
    modeled: false,
    complexity: 2,
    riskRating: 'elevated',
    entityTypes: ['c-corp', 's-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasEntity', op: 'eq', value: true }],
      reason: 'Real advisory work by family members can earn reasonable, documented fees.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['augusta-rule', 'hire-children'] },
  },
  {
    id: 'deferred-comp',
    name: 'Nonqualified Deferred Compensation for Owners',
    category: 'payroll-family',
    modeled: false,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['c-corp', 's-corp'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 400_000 }],
      reason: 'NQDC defers tax past qualified-plan limits — inside strict §409A guardrails.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['defined-benefit-plan'] },
  },
  {
    id: 'family-management-company',
    name: 'Family Management Company (FMC)',
    category: 'payroll-family',
    modeled: false,
    complexity: 4,
    riskRating: 'elevated',
    entityTypes: ['s-corp', 'partnership'],
    savingsBand: '5k-25k',
    effort: 'structural',
    suggest: {
      all: [
        { field: 'hasSCorp', op: 'eq', value: true },
        { field: 'dependentsUnder17', op: 'gt', value: 0 },
      ],
      reason: 'An FMC restores the FICA exemption for children working in a parent-run S-corp business — if it is real.',
    },
    interactions: { requires: ['hire-children'], conflictsWith: [], synergiesWith: ['kids-roth-ira'] },
  },
  {
    id: 'kiddie-tax-planning',
    name: 'Kiddie Tax Planning Around Child Wages',
    category: 'payroll-family',
    modeled: false,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['individual'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'dependentsUnder17', op: 'gt', value: 0 }],
      reason: 'Earned income avoids the kiddie tax; unearned income above the threshold does not.',
    },
    interactions: { requires: ['hire-children'], conflictsWith: [], synergiesWith: ['kids-roth-ira'] },
  },
  {
    id: 'kids-401k',
    name: '401(k) Contributions for Working Children',
    category: 'payroll-family',
    modeled: false,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership'],
    savingsBand: 'under-5k',
    effort: 'multi-step',
    suggest: {
      all: [
        { field: 'hasBusiness', op: 'eq', value: true },
        { field: 'dependentsUnder17', op: 'gt', value: 0 },
      ],
      reason: 'A working child with real wages can defer into the business plan on top of the standard deduction.',
    },
    interactions: { requires: ['hire-children'], conflictsWith: [], synergiesWith: ['kids-roth-ira', 'solo-401k'] },
  },
  {
    id: 'kids-roth-ira',
    name: "Roth IRA Funded by Kids' Earned Income",
    category: 'payroll-family',
    modeled: false,
    complexity: 1,
    riskRating: 'low',
    entityTypes: ['individual'],
    savingsBand: 'structural',
    effort: 'one-meeting',
    suggest: {
      all: [
        { field: 'hasBusiness', op: 'eq', value: true },
        { field: 'dependentsUnder17', op: 'gt', value: 0 },
      ],
      reason: 'Child wages already inside the standard deduction can seed decades of tax-free Roth growth.',
    },
    interactions: { requires: ['hire-children'], conflictsWith: [], synergiesWith: ['kids-401k'] },
  },
  {
    id: 'payroll-timing',
    name: 'Payroll & Bonus Timing',
    category: 'payroll-family',
    modeled: false,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'The 2.5-month accrued-bonus rule and year-end payroll runs are cheap timing levers.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['bracket-management'] },
  },
  {
    id: 'spouse-health-s-corp',
    name: 'S-Corp 2% Shareholder Health Insurance',
    category: 'payroll-family',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['s-corp'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    applyOrder: 31,
    inputs: inputs({ annualPremium: money() }),
    suggest: {
      all: [{ field: 'hasSCorp', op: 'eq', value: true }],
      reason: 'Premiums must run through the S-corp W-2 to preserve the above-the-line deduction.',
    },
    interactions: { requires: ['s-corp-election'], conflictsWith: [], synergiesWith: ['se-health-insurance', 'hsa-contributions'] },
    cases: [
      {
        name: 'mfj S-corp 300k/100k, 24k premiums routed',
        profile: SC300(),
        params: { annualPremium: 24_000 },
      },
      {
        name: 'single S-corp 200k/80k, 12k premiums routed',
        profile: SC200(),
        params: { annualPremium: 12_000 },
      },
    ],
  },
  {
    id: 'spouse-payroll',
    name: 'Adding Spouse to Payroll',
    category: 'payroll-family',
    modeled: true,
    complexity: 2,
    riskRating: 'moderate',
    entityTypes: ['sole-prop'],
    savingsBand: 'under-5k',
    effort: 'multi-step',
    applyOrder: 22,
    mayIncreaseBurden: true,
    inputs: inputs({ annualWages: money() }),
    suggest: {
      all: [
        { field: 'hasScheduleC', op: 'eq', value: true },
        { field: 'filingStatus', op: 'eq', value: 'mfj' },
      ],
      reason: 'Spouse wages are near-neutral on payroll tax — their value is the plans and benefits they unlock.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['section-105-merp', 'solo-401k'] },
    cases: [
      {
        name: 'mfj Sch C 200k, spouse at 30k',
        profile: base({ filingStatus: 'mfj', businesses: [schC(200_000)] }),
        params: { annualWages: 30_000 },
      },
      {
        name: 'mfj Sch C 300k, spouse at 50k',
        profile: CHC300(),
        params: { annualWages: 50_000 },
      },
    ],
  },

  // ═══ qbi-optimization ═══
  {
    id: 'multi-entity-qbi',
    name: 'Multi-Entity QBI Structuring',
    category: 'qbi-optimization',
    modeled: false,
    complexity: 5,
    riskRating: 'moderate',
    entityTypes: ['s-corp', 'partnership'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      all: [{ field: 'businesses.length', op: 'gt', value: 1 }],
      reason: 'Entity boundaries decide how the §199A wage and SSTB tests land across the group.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['qbi-aggregation', 'multi-entity-structuring'] },
  },
  {
    id: 'qbi-aggregation',
    name: '§199A Aggregation Election',
    category: 'qbi-optimization',
    modeled: true,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['s-corp', 'partnership'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    applyOrder: 15,
    inputs: inputs({}, []),
    suggest: {
      all: [
        { field: 'businesses.length', op: 'gt', value: 1 },
        { field: 'totalBusinessProfit', op: 'gt', value: 300_000 },
      ],
      reason: 'Aggregating commonly-controlled businesses pools W-2 wages for the §199A limit.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['qbi-wage-optimization', 'multi-entity-qbi'] },
    cases: [
      {
        name: 'mfj two S-corps: profit-rich/wage-poor + wage-rich',
        profile: base({
          filingStatus: 'mfj',
          businesses: [
            sCorp(500_000, 0, { id: 's1', name: 'HoldCo', employeeWages: 0 }),
            sCorp(100_000, 60_000, { id: 's2', name: 'OpCo', employeeWages: 150_000 }),
          ],
        }),
        params: {},
      },
      {
        name: 'mfj two S-corps, moderate wage imbalance',
        profile: base({
          filingStatus: 'mfj',
          businesses: [
            sCorp(400_000, 50_000, { id: 's1', name: 'A' }),
            sCorp(120_000, 40_000, { id: 's2', name: 'B', employeeWages: 90_000 }),
          ],
        }),
        params: {},
      },
    ],
  },
  {
    id: 'qbi-wage-optimization',
    name: '§199A W-2 Wage / UBIA Optimization',
    category: 'qbi-optimization',
    modeled: true,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['s-corp'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    applyOrder: 24,
    mayIncreaseBurden: true,
    inputs: inputs({ targetOwnerWages: money() }),
    suggest: {
      all: [
        { field: 'hasSCorp', op: 'eq', value: true },
        { field: 'totalBusinessProfit', op: 'gt', value: 300_000 },
      ],
      reason: 'Above the §199A threshold, owner W-2 becomes a dial: payroll tax against the wage limit.',
    },
    interactions: { requires: ['s-corp-election'], conflictsWith: [], synergiesWith: ['qbi-aggregation', 'reasonable-comp-study'] },
    cases: [
      {
        name: 'mfj S-corp 600k/60k comp raised to 150k for wage limit',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(600_000, 60_000)] }),
        params: { targetOwnerWages: 150_000 },
      },
      {
        name: 'mfj S-corp 500k/200k comp trimmed to 120k',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(500_000, 200_000)] }),
        params: { targetOwnerWages: 120_000 },
      },
    ],
  },
  {
    id: 'sstb-threshold-management',
    name: 'SSTB Threshold Management',
    category: 'qbi-optimization',
    modeled: true,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    applyOrder: 66,
    inputs: inputs({ incomeReduction: money() }),
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 200_000 }],
      reason: 'SSTB owners near the §199A phase-out can buy the deduction back with deliberate income compression.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['defined-benefit-plan', 'daf-bunching', 'solo-401k'] },
    cases: [
      {
        name: 'mfj SSTB Sch C 420k, 60k compression',
        profile: base({ filingStatus: 'mfj', businesses: [schC(420_000, { sstb: true })] }),
        params: { incomeReduction: 60_000 },
      },
      {
        name: 'single SSTB S-corp 260k/100k, 40k compression',
        profile: base({ businesses: [sCorp(260_000, 100_000, { sstb: true })] }),
        params: { incomeReduction: 40_000 },
      },
    ],
  },

  // ═══ real-estate ═══
  {
    id: 'bonus-depreciation',
    name: 'Bonus Depreciation Election (and Opt-Out Analysis)',
    category: 'real-estate',
    modeled: true,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp', 'rental'],
    savingsBand: '25k-100k',
    effort: 'multi-step',
    applyOrder: 37,
    inputs: inputs(
      {
        deductionAmount: money(),
        target: { type: 'string', enum: ['rental', 'business'] },
      },
      ['deductionAmount'],
    ),
    suggest: {
      any: [
        { field: 'hasRental', op: 'eq', value: true },
        { field: 'hasBusiness', op: 'eq', value: true },
      ],
      reason: '100% bonus is back for post-January 19, 2025 acquisitions — electing out is now the analysis.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['cost-segregation', 'qip-bonus', 'section-179-expensing'] },
    cases: [
      {
        name: 'mfj Sch C 300k, 80k equipment bonus',
        profile: CHC300(),
        params: { deductionAmount: 80_000, target: 'business' },
      },
      {
        name: 'mfj landlord, 40k bonus absorbs rental income, rest suspends',
        profile: base({ filingStatus: 'mfj', wages: 180_000, rentals: [rental(12_000)] }),
        params: { deductionAmount: 40_000, target: 'rental' },
      },
    ],
  },
  {
    id: 'cost-segregation',
    name: 'Cost Segregation Study',
    category: 'real-estate',
    modeled: true,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['rental', 's-corp', 'partnership'],
    savingsBand: '25k-100k',
    effort: 'multi-step',
    applyOrder: 37,
    inputs: inputs({ firstYearAcceleration: money() }),
    suggest: {
      all: [{ field: 'hasRental', op: 'eq', value: true }],
      reason: 'Reclassifying building components to 5/7/15-year lives front-loads depreciation — most potent with STR or REPS treatment.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['bonus-depreciation', 'str-loophole', 'reps-qualification', 'partial-asset-disposition'] },
    cases: [
      {
        name: 'mfj wages 180k, rental study 90k (passive-limited)',
        profile: base({ filingStatus: 'mfj', wages: 180_000, rentals: [rental(10_000)] }),
        params: { firstYearAcceleration: 90_000 },
      },
      {
        name: 'mfj wages 120k, rental study 60k, allowance in play',
        profile: base({ filingStatus: 'mfj', wages: 120_000, rentals: [rental(5_000)] }),
        params: { firstYearAcceleration: 60_000 },
      },
    ],
  },
  {
    id: 'energy-179d',
    name: '§179D Energy-Efficient Commercial Building Deduction',
    category: 'real-estate',
    modeled: true,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: '25k-100k',
    effort: 'multi-step',
    applyOrder: 38,
    inputs: inputs({ deductionAmount: money() }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Efficient commercial buildings placed in service before the OBBBA sunset still earn up to $5.81/sq ft.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['cost-segregation'] },
    cases: [
      {
        name: 'mfj S-corp 500k/150k, 100k §179D',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(500_000, 150_000)] }),
        params: { deductionAmount: 100_000 },
      },
      {
        name: 'mfj S-corp 300k/100k, 45k §179D',
        profile: SC300(),
        params: { deductionAmount: 45_000 },
      },
    ],
  },
  {
    id: 'grouping-election',
    name: 'Passive Activity Grouping Elections',
    category: 'real-estate',
    modeled: false,
    complexity: 3,
    riskRating: 'moderate',
    entityTypes: ['rental', 's-corp', 'partnership'],
    savingsBand: 'structural',
    effort: 'multi-step',
    suggest: {
      all: [{ field: 'rentals.length', op: 'gt', value: 1 }],
      reason: 'A Reg. §1.469-4 grouping can make material participation achievable across activities.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['reps-qualification', 'self-rental-structuring'] },
  },
  {
    id: 'installment-sale-property',
    name: 'Installment Sale (Property Dispositions)',
    category: 'real-estate',
    modeled: true,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['rental', 'individual'],
    savingsBand: '25k-100k',
    effort: 'multi-step',
    applyOrder: 63,
    inputs: inputs({
      totalGain: money(),
      termYears: { type: 'number', minimum: 2, maximum: 30 },
    }),
    suggest: {
      all: [
        { field: 'hasRental', op: 'eq', value: true },
        { field: 'longTermCapGain', op: 'gt', value: 100_000 },
      ],
      reason: 'Carrying the note on a property sale spreads gain recognition under §453 — depreciation recapture stays in year one.',
    },
    interactions: { requires: [], conflictsWith: ['like-kind-1031'], synergiesWith: ['bracket-management'] },
    cases: [
      {
        name: 'mfj landlord, 400k gain over 4 years',
        profile: base({ filingStatus: 'mfj', wages: 150_000, rentals: [rental(12_000)], longTermCapGain: 400_000 }),
        params: { totalGain: 400_000, termYears: 4 },
      },
      {
        name: 'single 250k gain over 5 years',
        profile: base({ wages: 100_000, longTermCapGain: 250_000 }),
        params: { totalGain: 250_000, termYears: 5 },
      },
    ],
  },
  {
    id: 'land-building-allocation',
    name: 'Land vs. Building Basis Allocation',
    category: 'real-estate',
    modeled: true,
    complexity: 2,
    riskRating: 'moderate',
    entityTypes: ['rental'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    applyOrder: 39,
    inputs: inputs({ additionalDepreciation: money() }),
    suggest: {
      all: [{ field: 'hasRental', op: 'eq', value: true }],
      reason: 'A defensible allocation beats the assessor default — more depreciable basis every year.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['cost-segregation'] },
    cases: [
      {
        name: 'mfj landlord, 6k extra annual depreciation',
        profile: base({ filingStatus: 'mfj', wages: 140_000, rentals: [rental(9_000)] }),
        params: { additionalDepreciation: 6_000 },
      },
      {
        name: 'single landlord, 3k extra depreciation',
        profile: base({ wages: 110_000, rentals: [rental(6_000)] }),
        params: { additionalDepreciation: 3_000 },
      },
    ],
  },
  {
    id: 'like-kind-1031',
    name: '1031 Like-Kind Exchange',
    category: 'real-estate',
    modeled: true,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['rental', 'individual'],
    savingsBand: '100k-plus',
    effort: 'structural',
    applyOrder: 61,
    inputs: inputs({ deferredGain: money() }),
    suggest: {
      all: [
        { field: 'hasRental', op: 'eq', value: true },
        { field: 'longTermCapGain', op: 'gt', value: 100_000 },
      ],
      reason: 'A qualified-intermediary exchange defers the whole gain into replacement property.',
    },
    interactions: { requires: [], conflictsWith: ['installment-sale-property', 'opportunity-zones'], synergiesWith: ['cost-segregation', 'basis-step-up-planning'] },
    cases: [
      {
        name: 'mfj landlord defers 500k gain',
        profile: base({ filingStatus: 'mfj', wages: 160_000, rentals: [rental(15_000)], longTermCapGain: 500_000 }),
        params: { deferredGain: 500_000 },
      },
      {
        name: 'single landlord defers 200k of 250k gain (boot)',
        profile: base({ wages: 120_000, rentals: [rental(8_000)], longTermCapGain: 250_000 }),
        params: { deferredGain: 200_000 },
      },
    ],
  },
  {
    id: 'opportunity-zones',
    name: 'Opportunity Zone Investment',
    category: 'real-estate',
    modeled: true,
    complexity: 5,
    riskRating: 'moderate',
    entityTypes: ['individual'],
    savingsBand: '100k-plus',
    effort: 'structural',
    applyOrder: 62,
    inputs: inputs({ investedGain: money() }),
    suggest: {
      all: [{ field: 'longTermCapGain', op: 'gt', value: 250_000 }],
      reason: 'Gains rolled into a QOF within 180 days defer tax and can grow tax-free after ten years.',
    },
    interactions: { requires: [], conflictsWith: ['like-kind-1031', 'installment-sale-business'], synergiesWith: [] },
    cases: [
      {
        name: 'mfj rolls 300k of gain into a QOF',
        profile: W2GAIN(),
        params: { investedGain: 300_000 },
      },
      {
        name: 'single rolls 150k of a 200k gain',
        profile: base({ wages: 180_000, longTermCapGain: 200_000 }),
        params: { investedGain: 150_000 },
      },
    ],
  },
  {
    id: 'partial-asset-disposition',
    name: 'Partial Asset Disposition on Renovations',
    category: 'real-estate',
    modeled: true,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['rental', 's-corp', 'partnership'],
    savingsBand: 'under-5k',
    effort: 'one-meeting',
    applyOrder: 39,
    inputs: inputs({ remainingBasis: money() }),
    suggest: {
      all: [{ field: 'hasRental', op: 'eq', value: true }],
      reason: 'Replacing a roof or HVAC lets the old component’s remaining basis deduct now — an election that expires with the return.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['repair-vs-capitalization', 'cost-segregation'] },
    cases: [
      {
        name: 'mfj landlord writes off 14k of old roof',
        profile: base({ filingStatus: 'mfj', wages: 130_000, rentals: [rental(11_000)] }),
        params: { remainingBasis: 14_000 },
      },
      {
        name: 'single landlord writes off 7k of old HVAC',
        profile: base({ wages: 100_000, rentals: [rental(7_000)] }),
        params: { remainingBasis: 7_000 },
      },
    ],
  },
  {
    id: 'qip-bonus',
    name: 'Qualified Improvement Property (QIP) Bonus',
    category: 'real-estate',
    modeled: true,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: '25k-100k',
    effort: 'multi-step',
    applyOrder: 37,
    inputs: inputs({ qipDeduction: money() }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Interior improvements to nonresidential buildings are 15-year property — fully bonus-eligible.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['bonus-depreciation', 'cost-segregation'] },
    cases: [
      {
        name: 'mfj S-corp 500k/150k, 120k build-out',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(500_000, 150_000)] }),
        params: { qipDeduction: 120_000 },
      },
      {
        name: 'mfj S-corp 300k/100k, 50k build-out',
        profile: SC300(),
        params: { qipDeduction: 50_000 },
      },
    ],
  },
  {
    id: 'repair-vs-capitalization',
    name: 'Repair vs. Capitalization (Tangible Property Regs)',
    category: 'real-estate',
    modeled: true,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['rental', 'sole-prop', 's-corp', 'partnership'],
    savingsBand: '5k-25k',
    effort: 'one-meeting',
    applyOrder: 36,
    inputs: inputs(
      {
        expensedAmount: money(),
        target: { type: 'string', enum: ['rental', 'business'] },
      },
      ['expensedAmount'],
    ),
    suggest: {
      any: [
        { field: 'hasRental', op: 'eq', value: true },
        { field: 'hasBusiness', op: 'eq', value: true },
      ],
      reason: 'The BAR/unit-of-property tests and safe harbors decide repair-now vs depreciate-over-decades.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['partial-asset-disposition'] },
    cases: [
      {
        name: 'mfj landlord expenses 18k of work',
        profile: base({ filingStatus: 'mfj', wages: 140_000, rentals: [rental(16_000)] }),
        params: { expensedAmount: 18_000, target: 'rental' },
      },
      {
        name: 'mfj Sch C expenses 10k of shop repairs',
        profile: CHC300(),
        params: { expensedAmount: 10_000, target: 'business' },
      },
    ],
  },
  {
    id: 'reps-qualification',
    name: 'Real Estate Professional Status (REPS)',
    category: 'real-estate',
    modeled: true,
    complexity: 4,
    riskRating: 'elevated',
    entityTypes: ['rental', 'individual'],
    savingsBand: '25k-100k',
    effort: 'structural',
    applyOrder: 43,
    inputs: inputs({}, []),
    suggest: {
      all: [
        { field: 'hasRental', op: 'eq', value: true },
        { field: 'wages', op: 'lt', value: 150_000 },
      ],
      reason: '750 documented hours and more-than-half of working time unlock rental losses against all income.',
    },
    interactions: { requires: [], conflictsWith: ['str-loophole'], synergiesWith: ['cost-segregation', 'grouping-election'] },
    cases: [
      {
        name: 'mfj spouse-REPS, 60k rental loss unlocked',
        profile: base({ filingStatus: 'mfj', wages: 140_000, rentals: [rental(-60_000)] }),
        params: {},
      },
      {
        name: 'mfj REPS with two rentals netting -35k',
        profile: base({
          filingStatus: 'mfj',
          wages: 120_000,
          rentals: [rental(-25_000), rental(-10_000, { id: 'r2', name: 'Rental 2' })],
        }),
        params: {},
      },
    ],
  },
  {
    id: 'section-179-expensing',
    name: 'Section 179 Expensing',
    category: 'real-estate',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership', 'c-corp'],
    savingsBand: '5k-25k',
    effort: 'one-meeting',
    applyOrder: 36,
    inputs: inputs({ electedAmount: money() }),
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: '§179 elects immediate expensing with asset-by-asset control — sharper than all-or-nothing bonus.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['bonus-depreciation', 'heavy-vehicle-179', 'equipment-timing'] },
    cases: [
      {
        name: 'mfj Sch C 300k, 60k elected',
        profile: CHC300(),
        params: { electedAmount: 60_000 },
      },
      {
        name: 'single S-corp 200k/80k, 25k elected',
        profile: SC200(),
        params: { electedAmount: 25_000 },
      },
    ],
  },
  {
    id: 'self-rental-recharacterization',
    name: 'Self-Rental Recharacterization Planning',
    category: 'real-estate',
    modeled: false,
    complexity: 3,
    riskRating: 'moderate',
    entityTypes: ['rental', 's-corp', 'partnership'],
    savingsBand: 'structural',
    effort: 'multi-step',
    suggest: {
      all: [
        { field: 'hasBusiness', op: 'eq', value: true },
        { field: 'hasRental', op: 'eq', value: true },
      ],
      reason: 'Self-rental income is recharacterized non-passive — rent-setting and grouping need design.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['self-rental-structuring', 'grouping-election'] },
  },
  {
    id: 'str-loophole',
    name: 'Short-Term Rental Strategy',
    category: 'real-estate',
    modeled: true,
    complexity: 4,
    riskRating: 'elevated',
    entityTypes: ['rental', 'individual'],
    savingsBand: '25k-100k',
    effort: 'structural',
    applyOrder: 42,
    inputs: inputs({ rentalId: { type: 'string' } }, []),
    suggest: {
      all: [{ field: 'hasRental', op: 'eq', value: true }],
      reason: 'Average stays of seven days or less plus material participation take an STR out of §469 without REPS.',
    },
    interactions: { requires: [], conflictsWith: ['reps-qualification'], synergiesWith: ['cost-segregation', 'bonus-depreciation'] },
    cases: [
      {
        name: 'mfj wages 250k, STR loss 45k unlocked',
        profile: base({ filingStatus: 'mfj', wages: 250_000, rentals: [rental(-45_000)] }),
        params: {},
      },
      {
        name: 'single wages 180k, STR loss 30k unlocked',
        profile: base({ wages: 180_000, rentals: [rental(-30_000)] }),
        params: {},
      },
    ],
  },

  // ═══ retirement ═══
  {
    id: 'backdoor-roth',
    name: 'Backdoor Roth IRA',
    category: 'retirement',
    modeled: false,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['individual'],
    savingsBand: 'structural',
    effort: 'one-meeting',
    suggest: {
      any: [
        { field: 'wages', op: 'gt', value: 150_000 },
        { field: 'totalBusinessProfit', op: 'gt', value: 150_000 },
      ],
      reason: 'Above the Roth income limits, the nondeductible-then-convert path still works — watch the pro-rata rule.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['mega-backdoor-roth', 'solo-401k'] },
  },
  {
    id: 'cash-balance-stack',
    name: 'Cash Balance Stacked on 401(k)/Profit Sharing',
    category: 'retirement',
    modeled: true,
    complexity: 5,
    riskRating: 'moderate',
    entityTypes: ['sole-prop', 's-corp', 'partnership'],
    savingsBand: '100k-plus',
    effort: 'structural',
    applyOrder: 54,
    inputs: inputs({ totalContribution: money() }),
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 500_000 }],
      reason: 'Stacking a cash balance plan on a 401(k) can shelter $200k–$400k+ for older high earners.',
    },
    interactions: { requires: [], conflictsWith: ['defined-benefit-plan'], synergiesWith: ['solo-401k', 'profit-sharing-new-comparability'] },
    cases: [
      {
        name: 'mfj Sch C 800k, 250k stacked',
        profile: base({ filingStatus: 'mfj', businesses: [schC(800_000)] }),
        params: { totalContribution: 250_000 },
      },
      {
        name: 'mfj S-corp 700k/300k comp, 200k stacked',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(700_000, 300_000)] }),
        params: { totalContribution: 200_000 },
      },
    ],
  },
  {
    id: 'defined-benefit-plan',
    name: 'Defined Benefit / Cash Balance Plan',
    category: 'retirement',
    modeled: true,
    complexity: 5,
    riskRating: 'moderate',
    entityTypes: ['sole-prop', 's-corp', 'partnership'],
    savingsBand: '100k-plus',
    effort: 'structural',
    applyOrder: 53,
    inputs: inputs({ annualContribution: money() }),
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 400_000 }],
      reason: 'A defined benefit plan converts high, steady profits into six-figure deductions.',
    },
    interactions: { requires: [], conflictsWith: ['cash-balance-stack'], synergiesWith: ['sstb-threshold-management'] },
    cases: [
      {
        name: 'mfj Sch C 700k, 180k DB funding',
        profile: base({ filingStatus: 'mfj', businesses: [schC(700_000)] }),
        params: { annualContribution: 180_000 },
      },
      {
        name: 'single S-corp 500k/250k comp, 120k DB funding',
        profile: base({ businesses: [sCorp(500_000, 250_000)] }),
        params: { annualContribution: 120_000 },
      },
    ],
  },
  {
    id: 'in-plan-roth-conversion',
    name: 'In-Plan Roth Conversions',
    category: 'retirement',
    modeled: false,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['individual'],
    savingsBand: 'structural',
    effort: 'multi-step',
    suggest: {
      all: [{ field: 'hasBusiness', op: 'eq', value: true }],
      reason: 'Low-bracket years are the window to convert pre-tax balances inside the plan.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['bracket-management', 'roth-vs-traditional-split'] },
  },
  {
    id: 'mega-backdoor-roth',
    name: 'Mega Backdoor Roth (After-Tax 401(k))',
    category: 'retirement',
    modeled: false,
    complexity: 4,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'individual'],
    savingsBand: 'structural',
    effort: 'multi-step',
    suggest: {
      any: [
        { field: 'totalBusinessProfit', op: 'gt', value: 300_000 },
        { field: 'wages', op: 'gt', value: 250_000 },
      ],
      reason: 'After-tax contributions up to the §415(c) ceiling can convert to Roth — plan document permitting.',
    },
    interactions: { requires: ['solo-401k'], conflictsWith: [], synergiesWith: ['backdoor-roth'] },
  },
  {
    id: 'profit-sharing-new-comparability',
    name: 'New Comparability Profit Sharing',
    category: 'retirement',
    modeled: true,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['s-corp', 'partnership', 'sole-prop'],
    savingsBand: '25k-100k',
    effort: 'structural',
    applyOrder: 52,
    inputs: inputs({ ownerAllocation: money() }),
    suggest: {
      all: [
        { field: 'hasEmployees', op: 'eq', value: true },
        { field: 'totalBusinessProfit', op: 'gt', value: 250_000 },
      ],
      reason: 'Cross-tested allocations tilt profit sharing toward older owners while staff minimums stay modest.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['cash-balance-stack', 'safe-harbor-401k'] },
    cases: [
      {
        name: 'mfj S-corp 500k/200k comp, 50k owner allocation',
        profile: base({ filingStatus: 'mfj', businesses: [sCorp(500_000, 200_000, { employeeWages: 120_000 })] }),
        params: { ownerAllocation: 50_000 },
      },
      {
        name: 'mfj Sch C 400k w/ staff, 60k owner allocation',
        profile: base({ filingStatus: 'mfj', businesses: [schC(400_000, { employeeWages: 90_000 })] }),
        params: { ownerAllocation: 60_000 },
      },
    ],
  },
  {
    id: 'roth-vs-traditional-split',
    name: 'Roth vs. Traditional 401(k) Split',
    category: 'retirement',
    modeled: false,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['individual'],
    savingsBand: 'structural',
    effort: 'one-meeting',
    suggest: {
      all: [{ field: 'filingStatus', op: 'exists' }],
      reason: 'The pre-tax vs Roth split is a bracket bet worth revisiting every year.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['bracket-management', 'in-plan-roth-conversion'] },
  },
  {
    id: 'safe-harbor-401k',
    name: 'Safe Harbor 401(k) Design',
    category: 'retirement',
    modeled: false,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'structural',
    effort: 'multi-step',
    suggest: {
      all: [{ field: 'hasEmployees', op: 'eq', value: true }],
      reason: 'A safe-harbor design buys out ADP/ACP testing so owners can defer the maximum.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['profit-sharing-new-comparability', 'cash-balance-stack'] },
  },
  {
    id: 'simple-ira',
    name: 'SIMPLE IRA',
    category: 'retirement',
    modeled: true,
    complexity: 2,
    riskRating: 'low',
    entityTypes: ['sole-prop', 's-corp', 'partnership'],
    savingsBand: '5k-25k',
    effort: 'multi-step',
    applyOrder: 51,
    inputs: inputs({ deferral: money() }),
    suggest: {
      all: [
        { field: 'hasBusiness', op: 'eq', value: true },
        { field: 'totalBusinessProfit', op: 'lt', value: 150_000 },
      ],
      reason: 'For modest profits with staff, SIMPLE beats a 401(k) on cost — below the solo-401(k) crossover.',
    },
    interactions: { requires: [], conflictsWith: ['solo-401k', 'sep-ira'], synergiesWith: [] },
    cases: [
      {
        name: 'single Sch C 90k, full deferral + match',
        profile: base({ businesses: [schC(90_000)] }),
        params: { deferral: 17_000 },
      },
      {
        name: 'mfj Sch C 120k, 10k deferral',
        profile: base({ filingStatus: 'mfj', businesses: [schC(120_000)] }),
        params: { deferral: 10_000 },
      },
    ],
  },

  // ═══ succession-exit ═══
  {
    id: 'annual-gifting-program',
    name: 'Systematic Gifting (Annual Exclusion + Lifetime Exemption)',
    category: 'succession-exit',
    modeled: false,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['individual'],
    savingsBand: 'structural',
    effort: 'multi-step',
    suggest: {
      all: [{ field: 'totalBusinessProfit', op: 'gt', value: 500_000 }],
      reason: 'Annual-exclusion gifts move appreciation out of the estate at zero transfer-tax cost.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['flp-gifting', 'basis-step-up-planning'] },
  },
  {
    id: 'basis-step-up-planning',
    name: 'Basis Step-Up Planning at Death',
    category: 'succession-exit',
    modeled: false,
    complexity: 3,
    riskRating: 'low',
    entityTypes: ['individual', 'rental'],
    savingsBand: 'structural',
    effort: 'multi-step',
    suggest: {
      any: [
        { field: 'hasRental', op: 'eq', value: true },
        { field: 'longTermCapGain', op: 'gt', value: 100_000 },
      ],
      reason: 'Low-basis assets held to death erase the built-in gain — sell-vs-hold needs that math.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['annual-gifting-program', 'like-kind-1031'] },
  },
  {
    id: 'buy-sell-agreement',
    name: 'Buy-Sell Agreement Funded with Life Insurance',
    category: 'succession-exit',
    modeled: false,
    complexity: 4,
    riskRating: 'moderate',
    entityTypes: ['s-corp', 'partnership', 'c-corp'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      all: [{ field: 'hasEntity', op: 'eq', value: true }],
      reason: 'Multi-owner businesses need a funded exit price before a death or dispute sets one — Connelly changed the math.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['esop-exit'] },
  },
  {
    id: 'esop-exit',
    name: 'ESOP Exit with §1042 Rollover',
    category: 'succession-exit',
    modeled: false,
    complexity: 5,
    riskRating: 'moderate',
    entityTypes: ['s-corp', 'c-corp'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      all: [
        { field: 'hasEmployees', op: 'eq', value: true },
        { field: 'totalBusinessProfit', op: 'gt', value: 750_000 },
      ],
      reason: 'Selling C-corp stock to an ESOP can defer the entire gain under §1042.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['buy-sell-agreement', 'c-corp-conversion'] },
  },
  {
    id: 'flp-gifting',
    name: 'Family Limited Partnership Valuation Discounts',
    category: 'succession-exit',
    modeled: false,
    complexity: 5,
    riskRating: 'elevated',
    entityTypes: ['partnership', 'rental'],
    savingsBand: 'structural',
    effort: 'structural',
    suggest: {
      any: [
        { field: 'rentals.length', op: 'gt', value: 1 },
        { field: 'totalBusinessProfit', op: 'gt', value: 750_000 },
      ],
      reason: 'Minority and marketability discounts compress the transfer-tax value of gifted interests.',
    },
    interactions: { requires: [], conflictsWith: [], synergiesWith: ['annual-gifting-program', 'idgt-installment-sale'] },
  },
];
